const C_NewmasterData = [
    {
        id: "2011NM-C001",
        nameTH: "ดริปโตซอรัส อคิลลังกิส",
        nameEN: "Dryptosaurus aquilunguis",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> ทิ้งการ์ด 1 ใบนำ Creature ตัวนี้เข้าสนาม ( Skill นี้ใช้ขณะการ์ดใบนี้อยู่บนมือ ) <br> • <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม > เราสามารถสั่งให้การ์ด 1 ใบได้รับสภาวะสับสน 1 เทิร์น`,
        image: "images/Newmaster/Dryptosaurus aquilunguis.jpg"
    },
    {
        id: "2011NM-C002",
        nameTH: "กวนหลง",
        nameEN: "Guanlong",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> ทิ้งการ์ด 1 ใบ นำ Creature ตัวนี้เข้าสนาม (Skill นี้ใช้ได้ขณะที่การ์ดนี้อยู่ในมือ)`,
        image: "images/Newmaster/Guanlong.jpg"
    },
    {
        id: "2011NM-C003",
        nameTH: "คาร์คาโรดอนโตอรัส ซาฮาริคัส",
        nameEN: "Carcharodontosaurus saharicus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้โจมตี > Creature ตัวนี้และตัวที่อยู่ในฝูงเดียวกัน ปรับ AT+200 จนจบเทิร์น.`,
        image: "images/Newmaster/Carcharodontosaurus saharicus.jpg"
    },
    {
        id: "2011NM-C004",
        nameTH: "อัลวาเรสซอรัส คัลวอย",
        nameEN: "Alvarezsaurus calvoi",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้โจมตีพร้อมกับ Creature ตัวอื่น 2 ตัวหรือมากกว่า > Creature ตัวนี้ปรับค่า AT+200/DF+100 เป็นเวลา 1 เทิร์น`,
        image: "images/Newmaster/Alvarezsaurus calvoi.jpg"
    },
    {
        id: "2011NM-C005",
        nameTH: "ซีโลไฟซิส บาอูรี",
        nameEN: "Coelophysis bauri",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อการ์ดใบนี้เข้ามาในสนาม > สามารถนำ Creature Card เผ่า สองขา ที่มี DP 3 หรือต่ำกว่า 1 ใบในมือเข้าสนามได้`,
        image: "images/Newmaster/Coelophysis bauri.jpg"
    },
	{
        id: "2011NM-C006",
        nameTH: "ยูเซ็นโทรซอรัส",
        nameEN: "Eucentrosaurus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อ Creature ใบนี้เข้ามาในสนาม > สามารถหา Armor Card ที่มี DP ไม่เกิน 3 จากในกอง แสดง นำขึ้นมือ สับเด็คของเรา <br> • <span class="hlmanual">Manual</span> จ่าย DP 3 จุด เลือก Armor 1 ใบ ในมือสวมใส่ให้กับ Creature ที่สวมใส่ได้หากไม่มี Creature ที่สวมใส่ได้ นำ Armor ดังกว่าเข้าสุสาน`,
        image: "images/Newmaster/Eucentrosaurus.jpg"
    },
    {
        id: "2011NM-C007",
        nameTH: "อาไรโนเซราทอปส์ บราคีออปส์",
        nameEN: "Arrhinoceratops brachyops",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> ตราบที่การ์ดใบนี้สวมใส่ Armor, Creature ตัวนี้มี "พร้อมรบ"(เจ้าของ Creature ตัวนี้สามารถสั่งการ Creature ตัวนี้ได้ในเทิร์นที่เพิ่งเข้ามาในสนาม) <br> • <span class="hlcont">Cont.</span> ตราบที่การ์ดใบนี้สวมใส่ Armor, Creature ตัวนี้มีปรับค่า AT + 200 / DF + 100`,
        image: "images/Newmaster/Arrhinoceratops brachyops.jpg"
    },
    {
        id: "2011NM-C008",
        nameTH: "ซูนิเซราทอปส์",
        nameEN: "Zuniceratops",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> "หลบฝูง" (ตราบที่การ์ดใบนี้อยู่ในตำแหน่งลูกฝูง เมื่อฝูงที่การ์ดใบนี้รวมอยู่จะถูกทำลายจากการต่อสู้ การ์ดใบนี้จะไม่ถูกทำลายตามไปด้วย) <br> • <span class="hlcont">Cont.</span> ตราบที่ Creature ตัวนี้รวมฝูง Creature ที่อยู่ในฝูงเดียวกับ Creature ตัวนี้ปรับค่า AT +200 DF + 200`,
        image: "images/Newmaster/Zuniceratops.jpg"
    },
    {
        id: "2011NM-C009",
        nameTH: "อวาเซราทอปปส์",
        nameEN: "Avaceratops",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> จ่าย DP 1 จุด Creature ตัวนี้ปรับค่า AT+100/DF+100 และยังสามารถโจมตีหรือป้องกันได้จนจบเทิร์น`,
        image: "images/Newmaster/Avaceratops.jpg"
    },
    {
        id: "2011NM-C010",
        nameTH: "บากาเซราทอปส์",
        nameEN: "Bagaceratops",
        dp: 1,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อ Creature นี้เข้ามาในสนาม เราสามารถดูการ์ดลำดับบนสุดของเด็คเรา 3 ใบเราสามารถเลือกการ์ด 1 ใบเข้า สุสาน แล้วเรียงกลับตามลำดับที่ต้องการ`,
        image: "images/Newmaster/Bagaceratops.jpg"
    },
	{
        id: "2011NM-C011",
        nameTH: "ไฮดราลโมซอรัส",
        nameEN: "Hydralmosaurus",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> Creature ที่เราควบคุมทั้งหมดปรับค่า AT+100/DF+100 <br> • <span class="hlmanual">Manual</span> จ่าย DP 1 จุด : Creature ตัวนี้ไม่ตกเป็นเป้าหมายการโจมตีจาก Creature ที่ยังไม่ได้รวมฝูงเป็นเวลาจนจบเทิร์น <br> • <span class="hlmanual">Manual</span> จ่าย DP 1 จุด : Creature ตัวนี้ไม่ตกเป็นเป้าหมายการโจมตีจากฝูงเป็นเวลาจนจบเทิร์น`,
		rarity: "Silver_Rare",
        image: "images/Newmaster/Hydralmosaurus.jpg"
    },
    {
        id: "2011NM-C012",
        nameTH: "คอลลาเวยาซอรัส",
        nameEN: "Callawayasaurus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 2 จุด : เราจั่วการ์ด 1 ใบ, เราทิ้งการ์ด 1 ใบ`,
        image: "images/Newmaster/Callawayasaurus.jpg"
    },
    {
        id: "2011NM-C013",
        nameTH: "คริปโตไครดัส",
        nameEN: "Cryptoclidus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> หลบฝูง (คู่ต่อสู้ไม่สามารถสร้างความเสียหายให้กับ Creature ที่มี Skill หลบฝูงได้ นอกเหนือจากจะสร้างความเสียหายให้กับสมาชิกตัวอื่นๆในฝูงดังกล่าวก่อน) <br> • <span class="hlcont">Cont.</span> Creature ตัวนี้ไม่สามารถมี สภาวะต่างปกติชนิดสับสน และ หลับ ได้`,
        image: "images/Newmaster/Cryptoclidus.jpg"
    },
    {
        id: "2011NM-C014",
        nameTH: "ทัวแรงกีซอรัส",
        nameEN: "Tuarangisaurus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 จุด + กำหนด Creature 1 เป้าหมาย : Creature เป้าหมายรับ สภาวะต่างปกติชนิดสับสน เป็นเวลา 1 เทิร์น <br> • <span class="hlmanual">Manual</span> จ่าย DP 3 จุด + กำหนด Creature 1 เป้าหมาย : Creature เป้าหมายรับ สภาวะต่างปกติชนิดหลับ เป็นเวลา 1 เทิร์น`,
        image: "images/Newmaster/Tuarangisaurus.jpg"
    },
    {
        id: "2011NM-C015",
        nameTH: "อโฟรซอรัส",
        nameEN: "Aphrosaurus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้มีสภาวะต่างปกติ > เราสามารถเลือก Creature 1 เป้าหมายที่ไม่ใช่ตัวมันเอง และ Creature ดังกล่าวรับ สภาวะต่างปกติชนิดสับสน เป็นเวลา 1 เทิร์น`,
        image: "images/Newmaster/Aphrosaurus.jpg"
    },

	{
        id: "2011NM-C016",
        nameTH: "เจ้อเจียงออปเทออัส",
        nameEN: "Zhejiangopterus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม เราสามารถกำหนด Field หรือ Magic บนสนาม 1 เป้าหมาย แล้วทำลายเป้าหมายและ Creature ตัวนี้ปรับค่า AT + 200 / DF + 200 เป็นเวลา 1 เทิร์น <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 จุด นำ Creature ใบนี้เข้ามือเจ้าของ`,
        image: "images/Newmaster/Zhejiangopterus.jpg"
    },
    {
        id: "2011NM-C017",
        nameTH: "เจิ้นหยวนออปเทออัส",
        nameEN: "Zhenyuanopterus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> "พร้อมรบ", จ่าย DP 1 จุด : Creature ตัวนี้ปรับค่า AT+200/DF+100 และยังสามารถโจมตีได้จนจบเทิร์น`,
        image: "images/Newmaster/Zhenyuanopterus.jpg"
    },
    {
        id: "2011NM-C018",
        nameTH: "เจอร์แมนโอแด๊กทิลอัส",
        nameEN: "Germanodactylus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> ทิ้งการ์ด 1 ใบ : เรารับ DP 1 จุด และ Creature ตัวนี้ยังสามารถโจมตีหรือป้องกันได้เป็นเวลาจนจบเทิร์น <br> • <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสุสานจากสนาม > เราสามารถเลือก Magic ในสุสานของเรา 1 ใบเข้ามือเจ้าของ`,
        image: "images/Newmaster/Germanodactylus.jpg"
    },
    {
        id: "2011NM-C019",
        nameTH: "แคมพีล็อคนาทัส",
        nameEN: "Campylognathus",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม > เราสามารถเรียก Magic Card ที่มี DP ค่าเรียก 3 จุดหรือต่ำกว่าจากมือถ้าสามารถทำได้ดยไม่เสียค่าเรียก`,
        image: "images/Newmaster/Campylognathus.jpg"
    },
    {
        id: "2011NM-C020",
        nameTH: "บาทราค๊อกนาทัส",
        nameEN: "Batrachognathus",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสุสานจากมือ > เรารับ DP 1 จุด`,
        image: "images/Newmaster/Batrachognathus.jpg"
    },
{
        id: "2011NM-C021",
        nameTH: "แอมพีโลซอรัส อาทาซิส",
        nameEN: "Ampelosaurus atacis",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนามจากการเรียก > ฟื้นฟู Creature ที่เราควบคุมทั้งหมด 100 จุด. <br> • <span class="hlmanual">Manual</span> จ่าย DP X จุด + กำหนด Creature 1 เป้าหมาย : ฟื้นฟู Creature เป้าหมาย X x 100 จุด.`,
        image: "images/Newmaster/Ampelosaurus atacis.jpg"
    },
    {
        id: "2011NM-C022",
        nameTH: "อโบรซอรัส ดงโปอิ",
        nameEN: "Abrosaurus dongpoi",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> ตราบที่ Creature ตัวนี้รวมฝูง, Creature ตัวอื่นที่รวมฝูงกับ Creature ตัวนี้ทั้งหมดปรับค่า AT+200 / DF+200. <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 จุด + กำหนด Creature 1 เป้าหมาย : ฟื้นฟู Creature เป้าหมาย 200 จุด.`,
        image: "images/Newmaster/Abrosaurus dongpoi.jpg"
    },
    {
        id: "2011NM-C023",
        nameTH: "โอพิสธูซีลีโคเดีย",
        nameEN: "Opisthocoelicaudia",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> ตราบที่เราควบคุม Creature เผ่าคอยาว 3 ตัวหรือมากกว่า, Creature ตัวนี้ปรับค่า AT+200/DF+200. <br> • <span class="hlcont">Cont.</span> ตราบที่ Creature ตัวนี้รวมฝูง, Creature ตัวนี้ ปรับค่า AT+200/DF+200.`,
        image: "images/Newmaster/Opisthocoelicaudia.jpg"
    },
    {
        id: "2011NM-C024",
        nameTH: "โซนิโดซอรัส",
        nameEN: "Sonidosaurus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 3 จุด : นำ Creature ตัวนี้สับเข้าเด็คของเรา, ค้นเด็คของเราหา Creature Card เผ่าคอยาว ที่มี DP ค่าเรียก 4 หรือต่ำกว่า, นำการ์ดดังกล่าวเข้าสนาม, สับเด็คของเรา.`,
        image: "images/Newmaster/Sonidosaurus.jpg"
    },
    {
        id: "2011NM-C025",
        nameTH: "มาสโซสปอนไดลัส คารินาทัส",
        nameEN: "Massospondylus carinatus",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 2 จุด : นำ Creature ตัวนี้สับเข้าเด็คของเรา, ค้นเด็คของเราหา Creature Card เผ่าคอยาวที่มี DP ค่าเรียก 3 หรือต่ำกว่า, นำการ์ดดังกล่าวเข้าสนาม, สับเด็คของเรา.`,
        image: "images/Newmaster/Massospondylus carinatus.jpg"
    },
	{
        id: "2011NM-C026",
        nameTH: "อันตาร์กโตเพลต้า โอลิเวรอย",
        nameEN: "Antarctopelta oliveroi",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> กำหนดเด็คผู้เล่นเป้าหมาย : นำการ์ด 2 ใบบนสุดของเด็คเป้าหมายลงสุสานและยังสามารถโจมตีได้เป็นเวลาจนจบเทิร์น <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 ทิ้งการ์ดใบนี้จากบนมือ กำหนด Creature 1 เป้าหมาย 1 ใบ ให้ Creature เป้าหมาย SH +600 เป็นเวลา 1 เทิร์น (Skill นี้ใช้ได้ขณะการ์ดใบนี้อยู่บนมือ)`,
        image: "images/Newmaster/Antarctopelta oliveroi.jpg"
    },
    {
        id: "2011NM-C027",
        nameTH: "เลกซ์โซวิซอรัส ดูโรบริฟเอนซิส",
        nameEN: "Lexovisaurus durobrivensis",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> จ่าย DP 3 + กำหนด Creature เผ่ามีเกราะหางหนาม 1 เป้าหมาย : Creature เป้าหมายปรับค่า DF+300 เป็นเวลาจนจบเกม (Skill นี้ใช้ได้ 1 ครั้งต่อเกม) <br> • <span class="hlcont">Cont.</span> ตราบใดที่การ์ดใบนี้รวมฝูงอยู่ Creature ใบอื่นที่รวมฝูงกับ Creature ใบนี้รับ DF+300`,
        image: "images/Newmaster/Lexovisaurus durobrivensis.jpg"
    },
    {
        id: "2011NM-C028",
        nameTH: "แดร็คโคเพลต้า ไซบิซิวสกี้",
        nameEN: "Dracopelta zbyzewskii",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 2 + ทิ้งการ์ดใบนี้จากบนมือ + กำหนด Creature 1 เป้าหมาย : ให้ Creature เป้าหมายมี SH+600 เป็นเวลา 1 เทิร์น (Skill นี้ใช้ได้ขณะการ์ดใบนี้อยู่บนมือ)`,
        image: "images/Newmaster/Dracopelta zbyzewskii.jpg"
    },
    {
        id: "2011NM-C029",
        nameTH: "ไฮเลโอซอรัส อามาฟัส",
        nameEN: "Hylaeosaurus armatus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> จ่าย DP 1 : Creature ใบนี้มี SH+200 เป็นเวลาจนจบเทิร์น (ใช้ Skill นี้ได้ 2 ครั้งต่อ 1 เทิร์น) <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 : Creature ใบนี้มี AT+100 เป็นเวลาจนจบเทิร์น (ใช้ Skill นี้ได้ 2 ครั้งต่อ 1 เทิร์น)`,
        image: "images/Newmaster/Hylaeosaurus armatus.jpg"
    },
    {
        id: "2011NM-C030",
        nameTH: "โนโดซอรัส เท็กทิลิส",
        nameEN: "Nodosaurus textilis",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> กำหนดเด็ค 1 เป้าหมาย นำการ์ดลำดับบนสุดของเด็คเป้าหมาย 3 ใบลงสุสาน และยังสามารถสั่งโจมตีได้เป็นเวลาจนจบเทิร์น`,
        image: "images/Newmaster/Nodosaurus textilis.jpg"
    },

    {
        id: "2011NM-C031",
        nameTH: "อเบลลิซอรัส โคมาฮูเอ็นซิส",
        nameEN: "Abelisaurus comahuensis",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้ต่อสู้สำเร็จ > เราสามารถค้นเด็คของเราหา Creature Card ที่มีวงศ์ [ Abelisauridae ] 1 ใบ > แสดง > นำมาขึ้นมือ > สับเด็คของเรา > ทิ้งการ์ด 2 ใบ`,
        image: "images/Newmaster/Abelisaurus comahuensis.jpg"
    },
    {
        id: "2011NM-C032",
        nameTH: "เดลตาโดรมิมัส โคมาฮูเอ็นซิส",
        nameEN: "Deltadromeus comahuensis",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้ตกเป็นเป้าหมายจาก Magic หรือ Skill > Creature ใบนี้ได้รับสภาวะตื่นตระหนก AT-200 1 เทิร์น`,
        image: "images/Newmaster/Deltadromeus comahuensis.jpg"
    },
    {
        id: "2011NM-C033",
        nameTH: "พิคโนนีโมซอรัส เนเวซี่",
        nameEN: "Pycnonemosaurus nevesi",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้ต่อสู่สำเร็จ > เราสามารถทิ้งการ์ด 2 ใบ แล้วนำ Creature Card ที่มีวงศ์ [Abelisauridae] ในมือเราเข้าสนาม 1 ใบ`,
        image: "images/Newmaster/Pycnonemosaurus nevesi.jpg"
    },
    {
        id: "2011NM-C034",
        nameTH: "ไทแรนโนไททัน ชูบูเท็นซิส",
        nameEN: "Tyrannotitan chubutensis",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> Creature ตัวนี้ไม่สามารถมีสถานะตื่นตระหนกได้ <br> • <span class="hlmanual">Manual</span> จ่าย DP 3 จุด + กำหนด Creature 1 เป้าหมาย : Creature เป้าหมาย ได้รับสภาวะตื่นตระหนก AT-200 เป็นเวลา 1 เทิร์นและ Creature ตัวนี้ยังสามารถโจมตีหรือป้องกันได้ในเทิร์นนี้`,
        rarity: "Silver_Rare",
        image: "images/Newmaster/Tyrannotitan chubutensis.jpg"
    },
    {
        id: "2011NM-C035",
        nameTH: "เดลตาโดรมิมัส โคมาฮูเอ็นซิส",
        nameEN: "Deltadromeus comahuensis",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้ตกเป็นเป้าหมายจาก Magic หรือ Skill > Creature ใบนี้ได้รับสภาวะตื่นตระหนก AT-200 1 เทิร์น`,
        rarity: "Silver_Rare",
		image: "images/Newmaster/Deltadromeus comahuensis035.jpg"
    },
    {
        id: "2011NM-C036",
        nameTH: "ทอร์โวซอรัส แทนเนรี่",
        nameEN: "Torvosaurus tanneri",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สองขา",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม > เรานำ Creature ที่มีชื่อว่า Torvosaurus จากมือเข้าสนาม 1 ใบ หากไม่มี เราสามารถจ่าย DP 2 จุด, แสดงการ์ดในมือ, ค้นเด็คของเราหาการ์ดชื่อ Torvosaurus 1 ใบแสดงนำมาขึ้นมือ สับเด็คของเรา`,
        image: "images/Newmaster/Torvosaurus tanneri.jpg"
    },
	{
        id: "2011NM-C037",
        nameTH: "เนโดเซราทอปส์",
        nameEN: "Nedoceratops",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 จุด + ทิ้ง Armor Card 1 ใบ : Creature ตัวนี้ปรับค่า AT + 500 จนจบเทิร์นและยังสามารถโจมตีหรือป้องกันได้จนจบเทิร์นนี้`,
        image: "images/Newmaster/Nedoceratops.jpg"
    },
    {
        id: "2011NM-C038",
        nameTH: "ไททันโนเซราทอปส์",
        nameEN: "Titanoceratops",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเขา",
        ability: ``,
        image: "images/Newmaster/Titanoceratops.jpg"
    },
	    {
        id: "2011NM-C039",
        nameTH: "ลิโบเน็กเทส",
        nameEN: "Libonectes",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสุสานจากสนาม > เราสามารถจ่าย DP 1 จุดแล้วค้นเด็คของเราหา Creature Card ที่มี [วงศ์ Elasmosauridae] 1 ใบ แสดง,นำขึ้นมือเจ้าของ สับเด็คของเรา ,เราทิ้งการ์ด 1 ใบ`,
		rarity: "Silver_Rare",
        image: "images/Newmaster/Libonectes.jpg"
    },
    {
        id: "2011NM-C040",
        nameTH: "ธาลาสโซเมดอน",
        nameEN: "Thalassomedon",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้ต่อสู้สำเร็จ > หากคู่ต่อสู้มีสถานะต่างปกติชนิดใดก็ตาม และ Creature ตัวนี้มี AT 400 หรือมากกว่าในขณะสำแดงผลของ Skill นี้ : ทำลายคู่ต่อสู้นั้น`,
        image: "images/Newmaster/Thalassomedon.jpg"
    },
    {
        id: "2011NM-C041",
        nameTH: "ธิลิลัว",
        nameEN: "Thililua",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อเข้าช่วง Draw Step > หากเราควบคุม Creature ที่มี [วงศ์ Leptocleididae] เท่านั้น เราจั่วการ์ด 1 ใบ`,
        image: "images/Newmaster/Thililua.jpg"
    },
    {
        id: "2011NM-C042",
        nameTH: "วูลังกาซอรัส",
        nameEN: "Woolungasaurus",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 2 จุด : นำ Creature ตัวนี้วางไว้ลำดับใต้สุดของเด็คเจ้าของ จั่วการ์ด 3 ใบ ทิ้งการ์ด 1 ใบ`,
        image: "images/Newmaster/Woolungasaurus.jpg"
    },
	    {
        id: "2011NM-C043",
        nameTH: "อาแรมโบเกียเนีย",
        nameEN: "Arambourgiania",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 3 จุด + กำหนด Magic 1 เป้าหมาย : ทำลาย Magic เป้าหมาย`,
        image: "images/Newmaster/Arambourgiania.jpg"
    },
    {
        id: "2011NM-C044",
        nameTH: "คาวกิเซฟาลัส",
        nameEN: "Caulkicephalus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> "พร้อมรบ" (ผู้ควบคุมสามารถสั่งการ Creature ตัวนี้ในเทิร์นที่พึ่งเข้าสนาม) <br> • <span class="hlmanual">Manual</span> จ่าย DP 2 จุด ; Creature ตัวนี้ปรับค่า AT + 400 จนจบเทิร์น และยังสามารถโจมตีหรือป้องกันได้ในเทิร์นนี้`,
        image: "images/Newmaster/Caulkicephalus.jpg"
    },
    {
        id: "2011NM-C045",
        nameTH: "ลาคัสโซวากัส",
        nameEN: "Lacusovagus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlmanual">Manual</span> เมื่อมีการเรียก Magic Card สามารถจ่ายค่าร่ายของ Creature นี้ : นำ Creature นี้เข้าสนามในการควบคุมของเราได้ <br> • <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม > ยกเลิก Magic Card ทั้งหมดอยู่ในกระบวนการเรียกนี้ หากมี Magic ถูกยกเลิกด้วย Skill นี้ เราจั่วการ์ด 1 ใบ`,
        image: "images/Newmaster/Lacusovagus.jpg"
    },
    {
        id: "2011NM-C046",
        nameTH: "ออนิโธแครัส",
        nameEN: "Ornithocheirus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> [AT Line] จ่าย DP 4 จุด+กำหนดผู้เล่น 1 เป้าหมาย : ผู้เล่นเป้าหมายเลือกทิ้งการ์ด 1 ใบ`,
        image: "images/Newmaster/Ornithocheirus.jpg"
    },
	    {
        id: "2011NM-C047",
        nameTH: "อาไกโรซอรัส",
        nameEN: "Argyrosaurus",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อการ์ดใบนี้เข้ามาในสนาม > เลือก creature 1 ใบ ฟื้นฟู creature ใบนั้นทั้งหมด <br> • <span class="hlmanual">Manual</span> จ่าย 2 DP : เราดูการ์ดลำดับบนสุดของเด็คเรา 3 ใบ, เลือก 1ใบขึ้นมือ, นําการ์ดที่เหลือลงสุสาน (สกิลนี้ใช้ได้1ครั้งต่อ1เกม)`,
		rarity: "Silver_Rare",
        image: "images/Newmaster/Argyrosaurus.jpg"
    },
    {
        id: "2011NM-C048",
        nameTH: "บาโรซอรัส",
        nameEN: "Barosaurus",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlauto">Auto</span> เมื่อเข้าสู่ช่วงเริ่มเทิร์น, หาก Creature ตัวนี้รวมฝูง Creature ตัวอื่นที่รวมฝูงกับ Creature ตัวนี้ทั้งหมดฟื้นฟู 100 จุด. <br> • <span class="hlmanual">Manual</span> จ่าย DP 1 จุด + กำหนดเด็คของเรา 1 เป้าหมาย เราดูการ์ดลำดับบนสุดของเด็คเรา 3 ใบ แล้วเรียงกลับตามลำดับที่ต้องการ.`,
        image: "images/Newmaster/Barosaurus.jpg"
    },
    {
        id: "2011NM-C049",
        nameTH: "ฟูตาลองโกซอรัส ดูไก",
        nameEN: "Futalongosaurus dukei",
        dp: 6,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: ``,
        image: "images/Newmaster/Futalongosaurus dukei.jpg"
    },
    {
        id: "2011NM-C050",
        nameTH: "เพอร์ตาซอรัส",
        nameEN: "Puertasaurus",
        dp: 6,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlcont">Cont.</span> ตราบที่เราควบคุม Creature ตัวนี้, Creature เผ่าคอยาว ที่เราควบคุมทั้งหมดไม่สามารถเป็นมีสถานะต่างปกติชนิดตื่นตระหนก และ สับสน ได้.`,
        image: "images/Newmaster/Puertasaurus.jpg"
    },
	{
        id: "2011NM-C051",
        nameTH: "อคันโธโฟลิส ฮอร์ริด้า",
        nameEN: "Acanthopholis horrida",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนามจากการเรียก > หากเราควบคุม Creature ที่มี [วงศ์ : Nodosauridae] 4 ใบขึ้นไป เราสามารถนำการ์ดลำดับบนสุดของเด็คใบก็ได้เข้าสุสานเจ้าของ 4 ใบ`,
        image: "images/Newmaster/Acanthopholis horrida.jpg"
    },
    {
        id: "2011NM-C052",
        nameTH: "ซีดาเพลต้า บิลเบฮอลโลรัม",
        nameEN: "Cedarpelta bilbeyhallorum",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ใบนี้ตกเป็นเป้าหมายการโจมตี Creature ใบนี้ปรับ AT+100 เป็นเวลาจนจบเทิร์น`,
        image: "images/Newmaster/Cedarpelta bilbeyhallorum.jpg"
    },
    {
        id: "2011NM-C053",
        nameTH: "อเลโตเพลต้า คูมสิ",
        nameEN: "Aletopelta coombsi",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ใบนี้ตกเป็นเป้าหมายการโจมตี Creature ใบนี้ปรับ AT+100 เป็นเวลาจนจบเทิร์น`,
        image: "images/Newmaster/Aletopelta coombsi.jpg"
    },
    {
        id: "2011NM-C054",
        nameTH: "คริช์ตันซอรัส โบลินี",
        nameEN: "Crichtonsaurus bohlini",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีเกราะหางหนาม",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> "หลบฝูง" <br> • <span class="hlauto">Auto</span> เมื่อมีการ์ดเข้าสุสานจากเด็ค > เรารับ DP 1 จุด`,
        rarity:"Silver_Rare",
		image: "images/Newmaster/Crichtonsaurus bohlini.jpg"
    },
    {
        id: "2011NM-C056",
        nameTH: "จีโอสเทิร์นเบอร์เกีย",
        nameEN: "Geosternbergia",
        dp: 3,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> นำการ์ดในสุสานของเราออกจากเกม 3 ใบ : เรานำ Magic Card ในสุสานเราเข้ามือเจ้าของ 1 ใบ`,
        image: "images/Newmaster/Geosternbergia.jpg"
    },
    {
        id: "2011NM-C057",
        nameTH: "อนูรอคนาทัส แอมโมนี่",
        nameEN: "Anurognathus ammoni",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlmanual">Manual</span> จ่าย DP 2 จุด + ทิ้งการ์ดใบนี้จากมือ > กำหนด Creature 1 เป้าหมาย : Creature เป้าหมายปรับค่า AT+600 เป็นเวลา 1 เทิร์น (Skill นี้ใช้ได้ขณะที่การ์ดใบนี้อยู่ในมือ)`,
        image: "images/Newmaster/Anurognathus ammoni.jpg"
    },
    {
        id: "2011NM-C058",
        nameTH: "ซอร์เดส",
        nameEN: "Sordes",
        dp: 2,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "มีปีก",
        ability: `<span class="hlabi">Skill :</span> <br> <span class="hlauto">Auto</span> เมื่อ Creature ตัวนี้เข้าสนาม > เราสามารถจ่าย DP 3 จุด + กำหนดผู้เล่น 1 เป้าหมายทิ้งการ์ด 1 ใบ`,
        image: "images/Newmaster/Sordes.jpg"
    },
	    {
        id: "2011NM-C059",
        nameTH: "มูอีซอรัส",
        nameEN: "Mauisaurus",
        dp: 4,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "สัตว์น้ำ",
        ability: ``,
        image: "images/Newmaster/Mauisaurus.jpg"
    },
	    {
        id: "2011NM-C060",
        nameTH: "คาธาร์เทซอรัส อเนียโรบิกา",
        nameEN: "Cathartesaurus anaerobica",
        dp: 5,
        type: "Creature",
        set: "นิวมาสเตอร์",
        clan: "คอยาว",
        ability: `<span class="hlabi">Skill :</span> <br> • <span class="hlcont">Cont.</span> ตราบที่เราควบคุม Creature เผ่าคอยาว 3 ตัวหรือมากกว่า Creature ตัวนี้ปรับค่า AT+300/DF+300 <br> • <span class="hlcont">Cont.</span> ตราบที่ Creature ตัวนี้รวมฝูง Creature ตัวนี้ ปรับค่า AT+200 / DF+200`,
        image: "images/Newmaster/Cathartesaurus anaerobica.jpg"
    },
];